CREATE TABLE PATIENT (
    PATIENT_ID NUMBER CONSTRAINT PK_PATIENT PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    DATE_OF_BIRTH DATE,
    EMAIL VARCHAR2(100),
    GENDER VARCHAR2(10),
    CONTACT_NO VARCHAR2(11) NOT NULL,
    ADDRESS VARCHAR2(100),
    CITY VARCHAR2(100)
);

describe patient;

CREATE TABLE ADMISSION (
    ADMISSION_ID NUMBER CONSTRAINT PK_ADMISSION PRIMARY KEY,
    DATE_OF_ADMISSION DATE,
    PATIENT_ID NUMBER NOT NULL,
    CONSTRAINT FK_ADMISSION FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

CREATE TABLE DEPARTMENT (
    ID NUMBER CONSTRAINT PK_DEPARTMENT PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE
);


CREATE TABLE DOCTOR (
    DOCTOR_ID NUMBER CONSTRAINT PK_DOCTOR PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    CONTACT_NO VARCHAR2(11),
    SPECIALITY VARCHAR2(100), -- MULTIPLE, COMMA-SEPARATED
    DEPARTMENT_ID NUMBER,
    CONSTRAINT FK_DOCTOR_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);

CREATE TABLE PRESCRIPTION (
    PRESCRIPTION_ID NUMBER CONSTRAINT PK_PRESCRIPTION PRIMARY KEY,
    PRESCRIPTION_DATE DATE,
    ADVICE VARCHAR2(500),
    ADMISSION_ID NUMBER,
    CONSTRAINT FK_PRESCRIPTION_ADMISSION FOREIGN KEY (ADMISSION_ID) REFERENCES ADMISSION (ADMISSION_ID)
);

CREATE TABLE MEDICINE (
    MEDICINE_ID NUMBER CONSTRAINT PK_MEDICINE PRIMARY KEY,
    TRADE_NAME VARCHAR2(50),
    GENERIC_NAME VARCHAR2(50),
    STRENGTH VARCHAR2(50), -- 500 mg, 625 mg
    DESCRIPTION VARCHAR2(500), -- COMPOSITION, DOSAGE, PRECAUTIONS
    MANUFACTURER VARCHAR2(50),
    PRICE NUMBER NOT NULL
);

CREATE TABLE MEDICINE_TAKEN (
    MEDICINE_ID NUMBER,
    QUANTITY NUMBER NOT NULL,
    TAKEN_DATE DATE,
    UNIT_COST NUMBER NOT NULL,
    ADMISSION_ID NUMBER,
    CONSTRAINT FK_MEDICINE_TAKEN_MEDICINE FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE (MEDICINE_ID),
    CONSTRAINT FK_MEDICINE_TAKEN_ADMISSION FOREIGN KEY (ADMISSION_ID) REFERENCES ADMISSION (ADMISSION_ID),
    PRIMARY KEY (MEDICINE_ID, ADMISSION_ID)
);

CREATE TABLE SURGERY (
    SURGERY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE,
    COST NUMBER NOT NULL
);
SELECT * FROM SURGERY;

CREATE TABLE SURGERY_TAKEN (
    TAKEN_DATE DATE,
    COST NUMBER NOT NULL,
    SURGERY_ID NUMBER,
    ADMISSION_ID NUMBER,
    CONSTRAINT FK_SURGERY_TAKEN_SURGERY FOREIGN KEY (SURGERY_ID) REFERENCES SURGERY (SURGERY_ID),
    CONSTRAINT FK_SURGERY_TAKEN_ADMISSION FOREIGN KEY (ADMISSION_ID) REFERENCES ADMISSION (ADMISSION_ID),
    PRIMARY KEY (SURGERY_ID, ADMISSION_ID)
);

CREATE TABLE TEST (
    TEST_ID NUMBER PRIMARY KEY,
    TYPE VARCHAR2(500) NOT NULL,
    DESCRIPTION VARCHAR2(500), -- WHAT TYPE OF TEST
    COST NUMBER NOT NULL
);

CREATE TABLE TEST_TAKEN (
    TAKEN_DATE DATE NOT NULL,
    COST NUMBER NOT NULL,
    REPORT BLOB NOT NULL, -- IN PDF FORM = BLOB
    ADMISSION_ID NUMBER,
    TEST_ID NUMBER,
    CONSTRAINT FK_TEST_TAKEN_ADMISSION FOREIGN KEY (ADMISSION_ID) REFERENCES ADMISSION (ADMISSION_ID),
    CONSTRAINT FK_TEST_TAKEN_TEST FOREIGN KEY (TEST_ID) REFERENCES TEST (TEST_ID)
);

CREATE TABLE ROOM (
    ROOM_ID NUMBER PRIMARY KEY,
    ROOM_NAME VARCHAR2(50) NOT NULL, -- f20 g09
    CAPACITY NUMBER, -- THIS IS A DERIVED ATTRIBUTE
    ROOM_TYPE VARCHAR2(50) NOT NULL -- WARD, CABIN
);

CREATE TABLE BED (
    BED_ID NUMBER PRIMARY KEY,
    BED_NUMBER VARCHAR2(10), -- 2A 2B 23C 23B AND SO ON (WHERE, IN 23A, 23 IS THE ROOM NUMBER)
    COST_PER_NIGHT NUMBER,
    ROOM_ID NUMBER,
    CONSTRAINT FK_BED_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID)
);

CREATE TABLE BED_TAKEN (
    BED_TAKEN_ID NUMBER PRIMARY KEY,
    BED_ID NUMBER,
    START_DATE DATE,
    END_DATE DATE,
    COST NUMBER,
    ADMISSION_ID NUMBER,
    CONSTRAINT FK_BED_TAKEN_BED FOREIGN KEY (BED_ID) REFERENCES BED (BED_ID),
    CONSTRAINT FK_BED_TAKEN_ADMISSION FOREIGN KEY (ADMISSION_ID) REFERENCES ADMISSION (ADMISSION_ID)
);



SELECT A.ADMISSION_ID, TO_CHAR(A.DATE_OF_ADMISSION, 'DD/MM/YYYY'), P.* FROM ADMISSION A LEFT OUTER JOIN PATIENT P ON A.PATIENT_ID = P.PATIENT_ID order BY A.ADMISSION_ID;












-- Insert statements for beds in ward rooms (Room IDs 1 to 26)
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('1A', 50, 1);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('1B', 50, 1);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('1C', 50, 1);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('2A', 50, 2);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('2B', 50, 2);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('2C', 50, 2);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('3A', 50, 3);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('3B', 50, 3);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('3C', 50, 3);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('4A', 50, 4);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('4B', 50, 4);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('4C', 50, 4);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('5A', 50, 5);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('5B', 50, 5);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('5C', 50, 5);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('6A', 50, 6);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('6B', 50, 6);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('6C', 50, 6);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('7A', 50, 7);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('7B', 50, 7);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('7C', 50, 7);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('8A', 50, 8);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('8B', 50, 8);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('8C', 50, 8);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('9A', 50, 9);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('9B', 50, 9);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('9C', 50, 9);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('10A', 50, 10);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('10B', 50, 10);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('10C', 50, 10);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('11A', 50, 11);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('11B', 50, 11);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('11C', 50, 11);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('12A', 50, 12);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('12B', 50, 12);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('12C', 50, 12);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('13A', 50, 13);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('13B', 50, 13);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('13C', 50, 13);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('14A', 50, 14);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('14B', 50, 14);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('14C', 50, 14);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('15A', 50, 15);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('15B', 50, 15);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('15C', 50, 15);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('16A', 50, 16);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('16B', 50, 16);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('16C', 50, 16);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('17A', 50, 17);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('17B', 50, 17);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('17C', 50, 17);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('18A', 50, 18);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('18B', 50, 18);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('18C', 50, 18);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('19A', 50, 19);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('19B', 50, 19);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('19C', 50, 19);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('20A', 50, 20);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('20B', 50, 20);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('20C', 50, 20);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('21A', 50, 21);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('21B', 50, 21);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('21C', 50, 21);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('22A', 50, 22);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('22B', 50, 22);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('22C', 50, 22);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('23A', 50, 23);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('23B', 50, 23);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('23C', 50, 23);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('24A', 50, 24);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('24B', 50, 24);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('24C', 50, 24);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('25A', 50, 25);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('25B', 50, 25);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('25C', 50, 25);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('26A', 50, 26);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('26B', 50, 26);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('26C', 50, 26);









-- Insert statements for beds in cabin rooms (Room IDs 27 to 55)
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('27A', 100, 27);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('28A', 100, 28);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('29A', 100, 29);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('30A', 100, 30);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('31A', 100, 31);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('32A', 100, 32);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('33A', 100, 33);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('34A', 100, 34);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('35A', 100, 35);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('36A', 100, 36);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('37A', 100, 37);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('38A', 100, 38);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('39A', 100, 39);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('40A', 100, 40);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('41A', 100, 41);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('42A', 100, 42);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('43A', 100, 43);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('44A', 100, 44);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('45A', 100, 45);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('46A', 100, 46);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('47A', 100, 47);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('48A', 100, 48);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('49A', 100, 49);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('50A', 100, 50);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('51A', 100, 51);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('52A', 100, 52);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('53A', 100, 53);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('54A', 100, 54);
INSERT INTO BED (BED_NUMBER, COST_PER_NIGHT, ROOM_ID) VALUES ('55A', 100, 55);






-- MONTHLY REVENUE
SELECT 
    TO_CHAR(taken_date, 'YYYY MONTH') AS month_year,
    TO_CHAR(TAKEN_DATE, 'YYYY MM'),
    SUM(quantity) AS total_quantity,
    SUM(quantity * unit_cost) AS total_cost
FROM 
    MEDICINE_TAKEN
WHERE 
    taken_date BETWEEN DATE '2021-01-01' AND DATE '2024-12-31'
GROUP BY 
    --TO_CHAR(taken_date, 'YYYY-MM')
    TO_CHAR(taken_date, 'YYYY MONTH'), TO_CHAR(TAKEN_DATE, 'YYYY MM')
ORDER BY TO_CHAR(TAKEN_DATE, 'YYYY MM') DESC;
    --month_year DESC;

select * FROM MEDICINE_TAKEN;




SELECT
    MEDICINE_ID--, SUM(UNIT_COST)
FROM
    (
        SELECT
            MEDICINE_ID,
            SUM (UNIT_COST),
            SUM(quantity) AS total_quantity
        FROM
            MEDICINE_TAKEN
        WHERE
            TO_CHAR(taken_date, 'YYYY-MM') = '2022-02' -- Replace '2022-02' with the desired month
        GROUP BY
            MEDICINE_ID
        ORDER BY
            total_quantity DESC
    )
WHERE
    ROWNUM = 1;




WITH TopMedicine AS (
    SELECT
        MEDICINE_ID,
        SUM(quantity) AS total_quantity,
        sum(unit_cost) as total_cost
    FROM
        MEDICINE_TAKEN
    WHERE
        TO_CHAR(taken_date, 'YYYY-MM') = '2022-02' -- Replace '2022-02' with the desired month
    GROUP BY
        MEDICINE_ID
    ORDER BY
        total_cost DESC
    FETCH FIRST 1 ROWS ONLY
)
SELECT
    T.MEDICINE_ID,
    T.total_quantity,
    m.unit_cost,
    T.total_quantity * M.UNIT_COST AS total_cost
FROM
    TopMedicine T
JOIN
    MEDICINE_taken M ON T.MEDICINE_ID = M.MEDICINE_ID;



SELECT * FROM( SELECT M.MEDICINE_ID MEDID, (M.TRADE_NAME || ' [' || (M.GENERIC_NAME || ' (' || M.STRENGTH ||')') || ']') NEM, SUM(MT.QUANTITY) Q, SUM(MT.UNIT_COST*MT.QUANTITY) REVENUE FROM MEDICINE_TAKEN MT JOIN MEDICINE M ON M.MEDICINE_ID = MT.MEDICINE_ID WHERE TO_CHAR(MT.TAKEN_DATE, 'MM, YYYY') = '06, 2021' GROUP BY M.MEDICINE_ID, M.TRADE_NAME, (M.GENERIC_NAME || ' (' || M.STRENGTH || ')') ORDER BY SUM(MT.UNIT_COST*MT.QUANTITY) DESC) WHERE ROWNUM <= 10;


SELECT * 
FROM MEDICINE_TAKEN
WHERE TO_CHAR(TAKEN_DATE, 'MM, YYYY') = '02, 2024';